site_name: MEDHIRA RN TypeScript Hooks
site_url: https://medhira-rn-typescript-hooks.readthedocs.io
site_description: React Native TypeScript validation hooks
site_author: MEDHIRA
docs_dir: docs

repo_name: HELLOMEDHIRA/medhira-rn-typescript-hooks
repo_url: https://github.com/HELLOMEDHIRA/medhira-rn-typescript-hooks

theme:
  name: material
  logo: https://raw.githubusercontent.com/HELLOMEDHIRA/medhira/main/assets/medhira-logo.png
  favicon: https://raw.githubusercontent.com/HELLOMEDHIRA/medhira/main/assets/medhira-logo.png
  palette:
    - scheme: default
      primary: teal
      accent: teal
    - scheme: slate
      primary: teal
      accent: teal

nav:
  - Getting Started: index.md
  - API: api.md
  - Examples: examples.md
  - About: about.md

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - tables
  - fenced_code
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search:
      lang: en
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
      cache_safe: true

copyright: |
  &copy; 2024 MEDHIRA. All rights reserved.